openapi: "3.0.1"
info:
  title: "Julink API"
  version: "0.0.1"

paths:
  /:
    post:
      security:
        - api_key: []
      responses:
        "200":
          description: "Success"
        "403":
          description: "Forbidden"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        # yes, you need the full uri
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_function_arn}/invocations"
        passthroughBehavior: "when_no_match"

    options:
      responses:
        "200":
          description: "Success"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
      x-amazon-apigateway-integration:
        type: "mock"
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "${cors_origin}"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key'"

components:
  securitySchemes:
    api_key:
      type: "apiKey"
      # header is case-sensitive.
      name: "x-api-key"
      in: "header"
      x-amazon-apigateway-api-key-source : "HEADER"